version: "3.8"
services:
  api1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:3000"
    environment:
      - NODE_ENV=production
    container_name: app1cheese
    command: npx sequelize-cli db:migrate
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  api2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:3000"
    environment:
      - NODE_ENV=production
    container_name: app2cheese
    command: npx sequelize-cli db:migrate
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  api3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8092:3000"
    environment:
      - NODE_ENV=production
    container_name: app3cheese
    command: npx sequelize-cli db:migrate
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
